"""constants"""

# pygame graphics
CAPTION = 'uncharted waters 2'
WINDOW_WIDTH = 400 + 110*2
WINDOW_HIGHT = 400
FPS = 30.0
FONT_SIZE = 18

# gui graphics
BUTTON_WIDTH, BUTTON_HIGHT = 60, 30
SELECTION_LIST_WIDTH, SELECTION_LIST_HIGHT = 225 , 250
SELECTION_LIST_X, SELECTION_LIST_Y = WINDOW_WIDTH - SELECTION_LIST_WIDTH, 120

PORT_MAP_SIZE = 96 * 3

# assets
HUD_WIDTH, HUD_HIGHT = 110, 400
BUILDING_PERSON_WIDTH, BUILDING_PERSON_HIGHT = 138, 114
BUILDING_CHAT_WIDTH, BUILDING_CHAT_HIGHT = 480, 129

# daemon mode (print to STDOUT?)
DAEMON_MODE = True

# Database
SAVE_ON_CONNECTION_LOST = True
SET_ONLINE_TO_TRUE_ON_LOGIN = True

# network
REMOTE_ON = True
HOST = 'localhost'
PORT = 8082
REMOTE_HOST = '129.28.172.72'
REMOTE_PORT = 8082

HEADER_SIZE = 4

# color
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
YELLOW = (255, 255, 0)
RED = (255, 0, 0)

# player data
PIXELS_COVERED_EACH_MOVE = 16
MOVE_TIME_INVERVAL = 0.01
DEVELOPER_MODE_ON = False

# in battle
BATTLE_TILE_SIZE = 32
THINK_TIME_IN_BATTLE = 30
MAX_STEPS_IN_BATTLE = 6
SHOOT_RANGE_IN_BATTLE = 4
ENGAGE_DAMAGE = 1
SHOOT_DAMAGE = 1


# world constants
SUPPLY_UNIT_COST = 5
SUPPLY_CONSUMPTION_PER_PERSON = 0.1 # 0.1
ONE_DAY_AT_SEA_IN_SECONDS = 3

# player image
SHIP_SIZE_IN_PIXEL = 32
PERSON_SIZE_IN_PIXEL = 32

FIGURE_WIDTH = 65
FIGURE_HIGHT = 81

ITEMS_IMAGE_SIZE = 49

# map data
WALKABLE_TILES = SAILABLE_TILES = set(range(1, 39))
PARTIAL_WORLD_MAP_TILES = 73
PARTIAL_WORLD_MAP_TILES_IN_ONE_DIRECTION = 36
PORT_TILES_COUNT = 96