villages_dict = {
    39: {
        'name': 'Prairie Dog',
        'y': 364,
        'x': 128,
        'latitude': '38N',
        'longitude': '128w',
        'description': "Ground-dwelling squirrel-like mammals 11 - 16 inches long. "
                       "They make their home underground in a complex system of interconnecting "
                       "burrows with many entrances.",
    },
    85: {
        'name': 'Moai',
        'y': 888,
        'x': 134,
        'latitude': '34S',
        'longitude': '127w',
        'description': "Giant stone statues ranging from 15 to 60 feet high. "
                       "They're carved with large faces, long ears and short bodies.",

    },
    40: {
        'name': 'Bison',
        'y': 430,
        'x': 168,
        'latitude': '29N',
        'longitude': '122w',
        'description': "A large wild bull that can weigh almost a ton. "
                       "It is hunted for both food and its hide, which can be used to make leather. "
                       "Such great numbers roam the plains that it's hard to imagine "
                       "them ever becoming extinct.",
    },
    49: {
        'name': 'Blue Whale',
        'y': 64,
        'x': 184,
        'latitude': '80N',
        'longitude': '119w',
        'description': "The largest animal in the world, sometimes "
                       "reaching a length of 30 metersand weighing over 150 tons.",
    },
    12: {
        'name': 'Mexican Beaded Lizard',
        'y': 460,
        'x': 202,
        'latitude': '25N',
        'longitude': '116w',
        'description': "A large lizard with black and yellow bead-like scales. "
                       "Its secret weapon is its ability to produce poison in its mouth.",
    },
    10: {
        'name': 'Monument of the Sun',
        'y': 494,
        'x': 228,
        'latitude': '20N',
        'longitude': '112w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    13: {
        'name': 'Stone Face',
        'y': 526,
        'x': 242,
        'latitude': '15N',
        'longitude': '109w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    11: {
        'name': 'Crystal Skull',
        'y': 542,
        'x': 266,
        'latitude': '13N',
        'longitude': '105w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    8: {
        'name': 'Jade Mask',
        'y': 504,
        'x': 280,
        'latitude': '18N',
        'longitude': '103w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    7: {
        'name': 'Popol Vuh',
        'y': 552,
        'x': 310,
        'latitude': '12N',
        'longitude': '98w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    44: {
        'name': "Venus' Flytrap",
        'y': 400,
        'x': 312,
        'latitude': '33N',
        'longitude': '98w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    87: {
        'name': 'Giant Tortoise',
        'y': 676,
        'x': 322,
        'latitude': '5S',
        'longitude': '96w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    43: {
        'name': 'Niagara Falls',
        'y': 332,
        'x': 336,
        'latitude': '42N',
        'longitude': '94w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    46: {
        'name': 'Mammoth',
        'y': 4,
        'x': 338,
        'latitude': '88N',
        'longitude': '93w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    14: {
        'name': 'Mural of Marnalico',
        'y': 576,
        'x': 344,
        'latitude': '8N',
        'longitude': '92w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    9: {
        'name': 'Guatavita Lake',
        'y': 554,
        'x': 354,
        'latitude': '11N',
        'longitude': '91w',
    },
    15: {
        'name': 'Stone Ball',
        'y': 608,
        'x': 382,
        'latitude': '4N',
        'longitude': '86w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    56: {
        'name': 'Temple of the Sun',
        'y': 710,
        'x': 386,
        'latitude': '9S',
        'longitude': '85w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    54: {
        'name': 'Terracotta Figure',
        'y': 630,
        'x': 398,
        'latitude': '1N',
        'longitude': '83w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    63: {
        'name': 'Gold Frog',
        'y': 676,
        'x': 398,
        'latitude': '5S',
        'longitude': '83w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    42: {
        'name': 'Totem Pole',
        'y': 430,
        'x': 404,
        'latitude': '29N',
        'longitude': '82w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    53: {
        'name': 'Vampire Bat',
        'y': 988,
        'x': 408,
        'latitude': '48S',
        'longitude': '82w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    60: {
        'name': 'Leon Penguin',
        'y': 1042,
        'x': 416,
        'latitude': '55S',
        'longitude': '80w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    41: {
        'name': 'Passenger Pigeon',
        'y': 386,
        'x': 432,
        'latitude': '35N',
        'longitude': '78w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    61: {
        'name': 'Archaeopteryx',
        'y': 694,
        'x': 432,
        'latitude': '7S',
        'longitude': '78w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    66: {
        'name': 'Tarantula',
        'y': 722,
        'x': 436,
        'latitude': '11S',
        'longitude': '77w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    55: {
        'name': 'Lake Titicaca',
        'y': 784,
        'x': 436,
        'latitude': '20S',
        'longitude': '77w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    62: {
        'name': 'Balsa',
        'y': 658,
        'x': 446,
        'latitude': '2S',
        'longitude': '75w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    69: {
        'name': 'Piranha',
        'y': 708,
        'x': 460,
        'latitude': '9S',
        'longitude': '73w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    64: {
        'name': 'Matamata',
        'y': 638,
        'x': 472,
        'latitude': '0N',
        'longitude': '71w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    72: {
        'name': 'Cactus',
        'y': 590,
        'x': 474,
        'latitude': '6N',
        'longitude': '71w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    59: {
        'name': 'Anteater',
        'y': 822,
        'x': 494,
        'latitude': '25S',
        'longitude': '67w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    65: {
        'name': 'Pororoca',
        'y': 682,
        'x': 500,
        'latitude': '5S',
        'longitude': '66w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    47: {
        'name': 'Saber-toothed Tiger',
        'y': 10,
        'x': 502,
        'latitude': '87N',
        'longitude': '66w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    71: {
        'name': 'Toucan',
        'y': 894,
        'x': 502,
        'latitude': '35S',
        'longitude': '66w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    70: {
        'name': 'Iguana',
        'y': 590,
        'x': 506,
        'latitude': '6N',
        'longitude': '65w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    58: {
        'name': 'Clay Monster',
        'y': 860,
        'x': 520,
        'latitude': '30S',
        'longitude': '63w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    68: {
        'name': 'Amazon Water Lily',
        'y': 670,
        'x': 530,
        'latitude': '4S',
        'longitude': '61w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    67: {
        'name': 'Anaconda',
        'y': 700,
        'x': 534,
        'latitude': '8S',
        'longitude': '61w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    57: {
        'name': 'Giant Ground Sloth',
        'y': 822,
        'x': 536,
        'latitude': '25S',
        'longitude': '60w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    45: {
        'name': 'Great Auk',
        'y': 166,
        'x': 728,
        'latitude': '65N',
        'longitude': '28w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    96: {
        'name': 'Clay Mosque',
        'y': 530,
        'x': 884,
        'latitude': '15N',
        'longitude': '2w',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    48: {
        'name': 'Stonehenge',
        'y': 270,
        'x': 888,
        'latitude': '51N',
        'longitude': '2w',
        'image_position': [10,4],
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    95: {
        'name': 'Ant Hill',
        'y': 550,
        'x': 914,
        'latitude': '12N',
        'longitude': '2e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    92: {
        'name': 'Diggos Monument',
        'y': 632,
        'x': 948,
        'latitude': '1N',
        'longitude': '8e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    94: {
        'name': 'Quagga',
        'y': 730,
        'x': 964,
        'latitude': '12S',
        'longitude': '10e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    91: {
        'name': 'Armadillo',
        'y': 688,
        'x': 974,
        'latitude': '6S',
        'longitude': '12e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    93: {
        'name': 'Moquele Mubembe',
        'y': 648,
        'x': 1002,
        'latitude': '1S',
        'longitude': '17e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    52: {
        'name': "Diaz's Monument",
        'y': 862,
        'x': 1016,
        'latitude': '30S',
        'longitude': '19e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    97: {
        'name': 'Moonbow',
        'y': 644,
        'x': 1050,
        'latitude': '0S',
        'longitude': '25e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    51: {
        'name': 'Big Zimbabwe',
        'y': 856,
        'x': 1050,
        'latitude': '30S',
        'longitude': '25e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    31: {
        'name': 'Rosetta Stone',
        'y': 418,
        'x': 1074,
        'latitude': '30N',
        'longitude': '29e',
        'description': """Black basalt slab bearing the same inscription in three languages- ancient Egyptian hieroglyphics, a simpler ancient Egyptian writing system, and Greek.""",
        'image_x': 16,
        'image_y': 2,
    },
    37: {
        'name': 'Khufu Pyramid',
        'y': 444,
        'x': 1084,
        'latitude': '27N',
        'longitude': '30e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    36: {
        'name': 'Baobab',
        'y': 566,
        'x': 1088,
        'latitude': '10N',
        'longitude': '31e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    34: {
        'name': 'Nubia Pyramid',
        'y': 536,
        'x': 1094,
        'latitude': '14N',
        'longitude': '32e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    38: {
        'name': 'Victoria Falls',
        'y': 640,
        'x': 1096,
        'latitude': '0N',
        'longitude': '32e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    33: {
        'name': 'Pteranodon',
        'y': 600,
        'x': 1102,
        'latitude': '5N',
        'longitude': '33e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    32: {
        'name': 'Crocodile',
        'y': 502,
        'x': 1106,
        'latitude': '19N',
        'longitude': '34e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    35: {
        'name': 'Tessisat Falls',
        'y': 562,
        'x': 1118,
        'latitude': '10N',
        'longitude': '36e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    30: {
        'name': 'Papyrus',
        'y': 460,
        'x': 1124,
        'latitude': '25N',
        'longitude': '37e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    16: {
        'name': 'Mandrill',
        'y': 644,
        'x': 1148,
        'latitude': '0S',
        'longitude': '41e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    27: {
        'name': 'Chameleon',
        'y': 712,
        'x': 1192,
        'latitude': '10S',
        'longitude': '48e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    29: {
        'name': 'Burning Water',
        'y': 422,
        'x': 1194,
        'latitude': '30N',
        'longitude': '49e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    28: {
        'name': 'Dodo',
        'y': 784,
        'x': 1204,
        'latitude': '20S',
        'longitude': '50e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    25: {
        'name': 'Mohenio-Daro',
        'y': 458,
        'x': 1292,
        'latitude': '25N',
        'longitude': '65e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    24: {
        'name': 'King Cobra',
        'y': 510,
        'x': 1338,
        'latitude': '18N',
        'longitude': '73e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    98: {
        'name': 'Aurora',
        'y': 2,
        'x': 1424,
        'latitude': '88N',
        'longitude': '87e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    26: {
        'name': 'Inle Lake',
        'y': 538,
        'x': 1458,
        'latitude': '14N',
        'longitude': '93e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    79: {
        'name': 'Hornbill',
        'y': 586,
        'x': 1472,
        'latitude': '7N',
        'longitude': '95e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    81: {
        'name': "Ayutthaya's Buddha",
        'y': 556,
        'x': 1486,
        'latitude': '11N',
        'longitude': '97e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    17: {
        'name': 'Panda',
        'y': 380,
        'x': 1514,
        'latitude': '36N',
        'longitude': '102e',
        'image_position': [5,1],
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    80: {
        'name': 'Angkor Wat',
        'y': 550,
        'x': 1516,
        'latitude': '12N',
        'longitude': '102e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    76: {
        'name': 'Borobudur',
        'y': 668,
        'x': 1530,
        'latitude': '3S',
        'longitude': '105e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    20: {
        'name': 'Hedgehog',
        'y': 364,
        'x': 1542,
        'latitude': '38N',
        'longitude': '107e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    73: {
        'name': 'Pitcher Plant',
        'y': 618,
        'x': 1548,
        'latitude': '3N',
        'longitude': '108e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    84: {
        'name': 'Kalavinka',
        'y': 478,
        'x': 1552,
        'latitude': '22N',
        'longitude': '108e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    18: {
        'name': 'Great Wall',
        'y': 342,
        'x': 1564,
        'latitude': '41N',
        'longitude': '110e',
        'image_position': [8,4],
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    77: {
        'name': 'Python',
        'y': 680,
        'x': 1566,
        'latitude': '5S',
        'longitude': '111e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    19: {
        'name': 'Qian Ling',
        'y': 390,
        'x': 1574,
        'latitude': '34N',
        'longitude': '112e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    5: {
        'name': 'Frilled Lizard',
        'y': 826,
        'x': 1582,
        'latitude': '25S',
        'longitude': '113e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    6: {
        'name': 'Kangaroo',
        'y': 760,
        'x': 1596,
        'latitude': '16S',
        'longitude': '116e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    74: {
        'name': 'Stone Buddha',
        'y': 642,
        'x': 1608,
        'latitude': '0S',
        'longitude': '118e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    75: {
        'name': 'Komodo Dragon',
        'y': 680,
        'x': 1620,
        'latitude': '5S',
        'longitude': '120e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    83: {
        'name': 'Tree Snake',
        'y': 532,
        'x': 1630,
        'latitude': '15N',
        'longitude': '121e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    23: {
        'name': 'Plant Worm',
        'y': 368,
        'x': 1656,
        'latitude': '37N',
        'longitude': '126e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    82: {
        'name': 'Durian',
        'y': 544,
        'x': 1658,
        'latitude': '13N',
        'longitude': '126e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    3: {
        'name': 'Ayers Rock',
        'y': 842,
        'x': 1658,
        'latitude': '28S',
        'longitude': '126e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    90: {
        'name': 'Fruit Bat',
        'y': 568,
        'x': 1710,
        'latitude': '10N',
        'longitude': '135e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    78: {
        'name': 'Greater Bird of Paradise',
        'y': 668,
        'x': 1722,
        'latitude': '3S',
        'longitude': '137e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    22: {
        'name': 'Toro Ruins',
        'y': 386,
        'x': 1730,
        'latitude': '35N',
        'longitude': '138e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    21: {
        'name': 'Namahage',
        'y': 356,
        'x': 1736,
        'latitude': '39N',
        'longitude': '139e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    1: {
        'name': 'Kiwi',
        'y': 732,
        'x': 1736,
        'latitude': '12S',
        'longitude': '139e',
        'description':"""Named for its cry, this is a flightless, nocturnal bird with a small head and a long, slender bill that has nostrils near the tip. It uses its highly developed sense of smell to find its food.""",
        'image_x':1,
        'image_y':1,
    },
    4: {
        'name': 'Tasmanian Devil',
        'y': 906,
        'x': 1764,
        'latitude': '36S',
        'longitude': '144e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    2: {
        'name': 'Koala',
        'y': 860,
        'x': 1788,
        'latitude': '30S',
        'longitude': '148e',
        'description': "A tree-dwelling marsupial mammal that only eats"
            " the leaves of the eucalyptus tree. Koala young spend "
            "their first 6 months in their mother's pouch, "
             "feeding on predigested eucalyptus leaves.",
        'image_x': 8,
        'image_y': 1,
    },
    88: {
        'name': 'Indo-Pacific Cowrie',
        'y': 592,
        'x': 1810,
        'latitude': '6N',
        'longitude': '151e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    89: {
        'name': 'Moa',
        'y': 890,
        'x': 1950,
        'latitude': '34S',
        'longitude': '175e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    86: {
        'name': 'Nasiped',
        'y': 732,
        'x': 1962,
        'latitude': '12S',
        'longitude': '177e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
    50: {
        'name': "Stellar's Sea Cow",
        'y': 94,
        'x': 1972,
        'latitude': '75N',
        'longitude': '178e',
        'description': "A large lizard with black and yellow bead-like scales. ",
    },
}

if __name__ == '__main__':
    a = villages_dict[1]
    print(a)
