hash_bible_quotes = {
    1: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil.",
    2: "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you.",
    3: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
    4: "And these words, which I command thee this day, shall be in thine heart: And thou shalt teach them diligently unto thy children, and shalt talk of them when thou sittest in thine house, and when thou walkest by the way, and when thou liest down, and when thou risest up.",
    5: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.",
    6: "Let all your things be done with charity.",
    7: "Commit thy works unto the Lord, and thy thoughts shall be established.",
    8: "The Lord bless thee, and keep thee: The Lord make his face shine upon thee, and be gracious unto thee: The Lord lift up his countenance upon thee, and give thee peace.",
    9: "Blessed is the man that trusteth in the Lord, and whose hope the Lord is. For he shall be as a tree planted by the waters, and that spreadeth out her roots by the river, and shall not see when heat cometh, but her leaf shall be green; and shall not be careful in the year of drought, neither shall cease from yielding fruit.",
    10: "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee.",

    11: "That he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit in the inner man; That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love.",
    12: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
    13: "But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
    14: "With all lowliness and meekness, with longsuffering, forbearing one another in love.",
    15: "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.",
    16: "For we walk by faith, not by sight.",
    17: "And ye shall serve the Lord your God, and he shall bless thy bread, and thy water; and I will take sickness away from the midst of thee.",
    18: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men; Knowing that of the Lord ye shall receive the reward of the inheritance: for ye serve the Lord Christ.",
    19: "And they said, Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house.",
    20: "Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",

    21: "Now faith is the substance of things hoped for, the evidence of things not seen.",
    22: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
    23: "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver.",
    24: "Grant thee according to thine own heart, and fulfil all thy counsel.",
    25: "Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart: So shalt thou find favour and good understanding in the sight of God and man.",
    26: "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live: And whosoever liveth and believeth in me shall never die. Believest thou this?",
    27: "And above all these things put on charity, which is the bond of perfectness.",
    28: "The Lord shall preserve thee from all evil: he shall preserve thy soul. The Lord shall preserve thy going out and thy coming in from this time forth, and even for evermore.",
    29: "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us.",
    30: "Fear not, for I art thy shield.",

    31: "And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God, and God in him.",
    32: "What time I am afraid, I will trust in thee.",
    33: "Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord.",
    34: "And now abideth faith, hope, charity, these three; but the greatest of these is charity.",
    35: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee: when thou walkest through the fire, thou shalt not be burned; neither shall the flame kindle upon thee.",
    36: "Rejoicing in hope; patient in tribulation; continuing instant in prayer.",
    37: "Jesus said unto him, If thou canst believe, all things are possible to him that believeth.",
    38: "He that covereth a transgression seeketh love; but he that repeateth a matter separateth very friends.",
    39: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.",
    40: "Continue in prayer, and watch in the same with thanksgiving.",

    41: "O Lord, thou art my God; I will exalt thee, I will praise thy name; for thou hast done wonderful things; thy counsels of old are faithfulness and truth.",
    42: "For ye are all the children of God by faith in Christ Jesus. For as many of you as have been baptized into Christ have put on Christ.",
    43: "Now I beseech you, brethren, by the name of our Lord Jesus Christ, that ye all speak the same thing, and that there be no divisions among you; but that ye be perfectly joined together in the same mind and in the same judgment.",
    44: "The liberal soul shall be made fat: and he that watereth shall be watered also himself.",
    45: "And the Lord, he it is that doth go before thee; he will be with thee, he will not fail thee, nor forsake thee: fear not, neither be dismayed.",
    46: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.",
    47: "See then that ye walk circumspectly, not as fools, but as wise, Redeeming the time, because the days are evil.",
    48: "Why art thou cast down, O my soul? and why art thou disquieted within me? hope thou in God: for I shall yet praise him, who is the health of my countenance, and my God.",
    49: "Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort; Who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble, by the comfort wherewith we ourselves are comforted of God.",
    50: "But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed.",

    51: "But who am I, and what is my people, that we should be able to offer so willingly after this sort? for all things come of thee, and of thine own have we given thee.",
    52: "But be ye doers of the word, and not hearers only, deceiving your own selves.",
    53: "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness: That the man of God may be perfect, thoroughly furnished unto all good works.",
    54: "Can a woman forget her sucking child, that she should not have compassion on the son of her womb? yea, they may forget, yet will I not forget thee. Behold, I have graven thee upon the palms of my hands; thy walls are continually before me.",
    55: "O give thanks unto the Lord; for he is good;for his mercy endureth for ever.",
    56: "Then shall ye call upon me, and ye shall go and pray unto me, and I will hearken unto you.",
    57: "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart.",
    58: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
    59: "Behold, how good and how pleasant it is for brethren to dwell together in unity!",
    60: "And let us consider one another to provoke unto love and to good works: Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another: and so much the more, as ye see the day approaching.",

    61: "He that followeth after righteousness and mercy findeth life, righteousness, and honour.",
    62: "And at midnight Paul and Silas prayed, and sang praises unto God: and the prisoners heard them.",
    63: "Know ye not that the unrighteous shall not inherit the kingdom of God? Be not deceived: neither fornicators, nor idolaters, nor adulterers, nor effeminate, nor abusers of themselves with mankind, Nor thieves, nor covetous, nor drunkards, nor revilers, nor extortioners, shall inherit the kingdom of God.",
    64: "For the Lord giveth wisdom: out of his mouth cometh knowledge and understanding.",
    65: "Train up a child in the way he should go: and when he is old, he will not depart from it.",
    66: "Wherefore comfort yourselves together, and edify one another, even as also ye do.",
    67: "For if ye forgive men their trespasses, your heavenly Father will also forgive you.",
    68: "Jesus saith unto her, Said I not unto thee, that, if thou wouldest believe, thou shouldest see the glory of God?",
    69: "Greater love hath no man than this, that a man lay down his life for his friends.",
    70: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law.",

    71: "And Jesus looking upon them saith, With men it is impossible, but not with God: for with God all things are possible.",
    72: "As in water face answereth to face, so the heart of man to man.",
    73: "We love him, because he first loved us.",
    74: "Let every thing that hath breath praise the Lord. Praise ye the Lord.",
    75: "My son, keep thy father's commandment, and forsake not the law of thy mother.",
    76: "Whose adorning let it not be that outward adorning of plaiting the hair, and of wearing of gold, or of putting on of apparel; But let it be the hidden man of the heart, in that which is not corruptible, even the ornament of a meek and quiet spirit, which is in the sight of God of great price.",
    77: "A man's gift maketh room for him, and bringeth him before great men.",
    78: "Call unto me, and I will answer thee, and show thee great and mighty things, which thou knowest not.",
    79: "Husbands, love your wives, even as Christ also loved the church, and gave himself for it; That he might sanctify and cleanse it with the washing of water by the word.",
    80: "For of him, and through him, and to him, are all things: to whom be glory for ever. Amen.",

    81: "Although the fig tree shall not blossom, neither shall fruit be in the vines; the labour of the olive shall fail, and the fields shall yield no meat; the flock shall be cut off from the fold, and there shall be no herd in the stalls: Yet I will rejoice in the Lord, I will joy in the God of my salvation.",
    82: "He healeth the broken in heart,and bindeth up their wounds.",
    83: "But thanks be to God, which giveth us the victory through our Lord Jesus Christ.",
    84: "But Jesus said, Suffer little children, and forbid them not, to come unto me: for of such is the kingdom of heaven.",
    85: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
    86: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
    87: "Keep thy heart with all diligence; for out of it are the issues of life.",
    88: "Thy word is a lamp unto my feet, and a light unto my path.",
    89: "For I the Lord thy God will hold thy right hand, saying unto thee, Fear not; I will help thee.",
    90: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.",

    91: "For where two or three are gathered together in my name, there am I in the midst of them.",
    92: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.",
    93: "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.",
    94: "But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you.",
    95: "I can do all things through Christ which strengtheneth me.",
    96: "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.",
    97: "Now the Lord is that Spirit: and where the Spirit of the Lord is, there is liberty.",
    98: "Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit, and that your fruit should remain: that whatsoever ye shall ask of the Father in my name, he may give it you.",
    99: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves.",
    100: "If my people, which are called by my name, shall humble themselves, and pray, and seek my face, and turn from their wicked ways; then will I hear from heaven, and will forgive their sin, and will heal their land.",

}